### PR TITLE
Binary message attributes support

### PR DESCRIPTION
**Pull request by brainoutsource**

### CODE REVIEW

**Comment by adamw** [comment]
Thanks! Looks great. Maybe you could add a simple integration test? See: https://github.com/adamw/elasticmq/blob/master/rest/rest-sqs-testing-amazon-java-sdk/src/test/scala/org/elasticmq/rest/sqs/AmazonJavaSdkTestSuite.scala

**Comment by brainoutsource** [comment]
Sure, np.

**Comment by brainoutsource** [comment]
Done

**Comment by adamw** [comment]
Thanks again, 0.8.9 released :)

**Comment by brainoutsource** [comment]
Can't see it at maven central yet :(

**Comment by adamw** [comment]
Sorry! I uploaded the binaries but didn't release to central - should be there in ~15 minutes

**Comment by brainoutsource** [comment]
Thank you!

**Pull request merged**
