### PR TITLE
Implement terraform support via localstack

### PR DESCRIPTION
**Pull request by mberlanda**
**Description**

I am trying to create resources on elasticmq using terraform.

My `main.tf`:

```tf
provider "aws" {
  region                      = "us-east-1"
  access_key                  = "anaccesskey"
  secret_key                  = "asecretkey"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  s3_force_path_style         = true

  endpoints {
    sqs      = "http://localhost:9324"
  }
}

resource "aws_sqs_queue" "terraform_queue_mq" {
  name                        = "terraform-queue-mq.fifo"
  fifo_queue                  = true
  content_based_deduplication = true
}

resource "aws_sqs_queue" "terraform_queue" {
  name                        = "my-queue"
}
```

Then running:

```bash
terraform init -input=false
terraform plan -input=false
terraform apply -input=false -auto-approve
```

I got:

```
Error: Error applying plan:

1 error(s) occurred:

* aws_sqs_queue.terraform_queue_mq: 1 error(s) occurred:

* aws_sqs_queue.terraform_queue_mq: [ERR] Error updating SQS attributes: InvalidAttributeName: InvalidAttributeName; see the SQS docs.
	status code: 400, request id: 00000000-0000-0000-0000-000000000000

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### CODE REVIEW

**Comment by mberlanda** [comment]
At the current state:

```
$ aws --endpoint-url=http://localhost:9324 sqs get-queue-attributes --queue-url "http://localhost:9324/queue/terraform-queue-mq.fifo" --attribute-names All
{
    "Attributes": {
        "VisibilityTimeout": "30",
        "DelaySeconds": "0",
        "ReceiveMessageWaitTimeSeconds": "0",
        "ApproximateNumberOfMessages": "0",
        "ApproximateNumberOfMessagesNotVisible": "0",
        "ApproximateNumberOfMessagesDelayed": "0",
        "CreatedTimestamp": "1533566380",
        "LastModifiedTimestamp": "1533566380",
        "QueueArn": "arn:aws:sqs:elasticmq:000000000000:terraform-queue-mq.fifo",
        "ContentBasedDeduplication": "true",
        "FifoQueue": "true"
    }
}

$ aws --endpoint-url=http://localhost:9324 sqs get-queue-attributes --queue-url "http://localhost:9324/queue/my-queue" --attribute-names All
{
    "Attributes": {
        "VisibilityTimeout": "30",
        "DelaySeconds": "0",
        "ReceiveMessageWaitTimeSeconds": "0",
        "ApproximateNumberOfMessages": "0",
        "ApproximateNumberOfMessagesNotVisible": "0",
        "ApproximateNumberOfMessagesDelayed": "0",
        "CreatedTimestamp": "1533566469",
        "LastModifiedTimestamp": "1533566469",
        "QueueArn": "arn:aws:sqs:elasticmq:000000000000:my-queue"
    }
}
```

**Comment by mberlanda** [comment]
It seems that elasticmq never has been compatible with terraform out of the box.

I always used it wrapped by localstack.
I tried to upgrade localstack image to use the latest version of elasticmq here: https://github.com/localstack/localstack/pull/880

I still get the following issue:

```
aws_sqs_queue.terraform_queue: Refreshing state... (ID: http://localhost:4576/queue/my-queue)
aws_sqs_queue.terraform_queue: Creating...
  arn:                               "" => "<computed>"
  content_based_deduplication:       "" => "false"
  delay_seconds:                     "" => "0"
  fifo_queue:                        "" => "false"
  kms_data_key_reuse_period_seconds: "" => "<computed>"
  max_message_size:                  "" => "262144"
  message_retention_seconds:         "" => "345600"
  name:                              "" => "my-queue"
  policy:                            "" => "<computed>"
  receive_wait_time_seconds:         "" => "0"
  visibility_timeout_seconds:        "" => "30"
aws_sqs_queue.terraform_queue_mq: Creating...
  arn:                               "" => "<computed>"
  content_based_deduplication:       "" => "true"
  delay_seconds:                     "" => "0"
  fifo_queue:                        "" => "true"
  kms_data_key_reuse_period_seconds: "" => "<computed>"
  max_message_size:                  "" => "262144"
  message_retention_seconds:         "" => "345600"
  name:                              "" => "terraform-queue-mq.fifo"
  policy:                            "" => "<computed>"
  receive_wait_time_seconds:         "" => "0"
  visibility_timeout_seconds:        "" => "30"
aws_sqs_queue.terraform_queue: Creation complete after 0s (ID: http://localhost:4576/queue/my-queue)

Error: Error applying plan:

1 error(s) occurred:

* aws_sqs_queue.terraform_queue_mq: 1 error(s) occurred:

* aws_sqs_queue.terraform_queue_mq: [ERR] Error updating SQS attributes: InvalidAttributeName: InvalidAttributeName; see the SQS docs.
	status code: 400, request id: 00000000-0000-0000-0000-000000000000
```

I build then a custom image out of the fatjar assembled with this pr:

```
aws_sqs_queue.terraform_queue: Refreshing state... (ID: http://localhost:4576/queue/my-queue)
aws_sqs_queue.terraform_queue_mq: Refreshing state... (ID: http://localhost:4576/queue/terraform-queue-mq.fifo)
aws_sqs_queue.terraform_queue: Creating...
  arn:                               "" => "<computed>"
  content_based_deduplication:       "" => "false"
  delay_seconds:                     "" => "0"
  fifo_queue:                        "" => "false"
  kms_data_key_reuse_period_seconds: "" => "<computed>"
  max_message_size:                  "" => "262144"
  message_retention_seconds:         "" => "345600"
  name:                              "" => "my-queue"
  policy:                            "" => "<computed>"
  receive_wait_time_seconds:         "" => "0"
  visibility_timeout_seconds:        "" => "30"
aws_sqs_queue.terraform_queue_mq: Creating...
  arn:                               "" => "<computed>"
  content_based_deduplication:       "" => "true"
  delay_seconds:                     "" => "0"
  fifo_queue:                        "" => "true"
  kms_data_key_reuse_period_seconds: "" => "<computed>"
  max_message_size:                  "" => "262144"
  message_retention_seconds:         "" => "345600"
  name:                              "" => "terraform-queue-mq.fifo"
  policy:                            "" => "<computed>"
  receive_wait_time_seconds:         "" => "0"
  visibility_timeout_seconds:        "" => "30"
aws_sqs_queue.terraform_queue: Creation complete after 0s (ID: http://localhost:4576/queue/my-queue)
aws_sqs_queue.terraform_queue_mq: Creation complete after 0s (ID: http://localhost:4576/queue/terraform-queue-mq.fifo)

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```

The issue was solved by mocking FIFO attributes as well

**Comment by adamw** [comment]
Thanks for the PR!

`ContentBasedDeduplication` and `FifoQueue`s are both supported, although not when reading queue directives - maybe it would be possible to add non-mocked support for them?

**Comment by mberlanda** [comment]
just rebased to fix conflicts

**Comment by adamw** [comment]
Released in 0.14.5, thanks!

**Comment by mberlanda** [comment]
thank you!

**Pull request merged**
