### PR TITLE
Add a simple Dockerfile

### PR DESCRIPTION
**Pull request by willejs**
Added a simple dockerfile so that people can easily build this into a container. 
As its using a file off S3, and not built in CI I have added checksumming too.

Ideally there would be some ci building the code and dockerfile and cutting releases, which im happy to do if i end up using this a lot.

### CODE REVIEW

**Comment by adamw** [comment]
Thanks! Maybe it would be more clear to save these files e.g. in a `docker` subdirectory instead of the root?

**Comment by adamw** [comment]
@willejs yes looks good, thanks! :)

**Comment by cajund** [comment]
Folks, are you or do you plan to generate an official container image and store it on Docker Hub? I noticed there are a number of other folks doing this, but I would rather use something directly from the source. It's an extra step, but it would be helpful. Thanks!

**Comment by adamw** [comment]
@cajund at some point, definitely, the backlog just needs to get a bit shorter ;)

**Pull request merged**
